--- pisi/archive.py~	2014-02-13 16:38:37.549954877 +0100
+++ pisi/archive.py	2014-02-13 16:32:28.000000000 +0100
@@ -410,6 +410,27 @@
                 # Try to extract again.
                 self.tar.extract(tarinfo)
 
+            except IOError, e:
+                # Handle the case where new path is file, but old path is directory
+                # due to not possible touch file c in /a/b if directory /a/b/c exists.  
+                if not e.errno == errno.EISDIR:
+                    path = tarinfo.name
+                    found = False
+                    while path:
+                        if os.path.isfile(path):
+                            os.unlink(path)
+                            found = True
+                            break
+                        else:
+                            path = "/".join(path.split("/")[:-1])
+                    if not found: raise
+                    # Try to extract again.
+                    self.tar.extract(tarinfo)
+                else:
+                    shutil.rmtree(tarinfo.name)
+                    # Try to extract again.
+                    self.tar.extract(tarinfo)
+
             # tarfile.extract does not honor umask. It must be honored
             # explicitly. See --no-same-permissions option of tar(1),
             # which is the deafult behaviour.
